In [158]:
import numpy
filename = '/home/shreeya/ml_library/data/iris-normalise-1.csv'
raw_data = open(filename,'rt')
data = numpy.loadtxt(raw_data,delimiter=",")

In [164]:
#split into training and test dataset
numpy.random.shuffle(data)
trainingData, testData = data[:60,:],data[60:,:]
print("Training data shape: \n")
print(trainingData.shape)
print("Test data shape: \n")
print(testData.shape)

Training data shape: 

(60, 5)
Test data shape: 

(40, 5)


In [165]:
theta0 = 0.0
updatedTheta0 = 0.0
m = trainingData.shape[0]
print('train m = ', m)
n = trainingData.shape[1]
print('train n = ', n)
theta1 = numpy.zeros((n-1,1))
updatedTheta1 = numpy.zeros((n-1,1))
print('Initial theta0 = ', theta0)
print('Initial theta1 = ')
for line in theta1:
    print(*line)
alpha = 0.3
print('alpha = ', alpha)

train m =  60
train n =  5
Initial theta0 =  0.0
Initial theta1 = 
0.0
0.0
0.0
0.0
alpha =  0.3


In [166]:
import math
def predict(theta0, theta1, dataForPred):
    predict = 0.0
    predict = theta0
    for j in range(n-1):
        predict = predict + (theta1[j]*dataForPred[j])
    predict = 1 / (1 + math.exp(-predict))
    return predict

In [167]:
#Stochastic Gradiant 
cost = 0.0
minCost = 0.0
error = 0.0
predictedY = 0.0
epochs = 4
trainingInstance = numpy.zeros((1,n-1))
print(trainingInstance.shape)

for begin in range(epochs):
    for i in range(m-1):
        trainingInstance = trainingData[i][0:n-1]
        print('Training Instance = ', trainingInstance)
        predictedY = predict(theta0, theta1, trainingInstance)
        print('PredictedY = ', predictedY)
        print('Actual Y= ', trainingData[i][n-1])
        error = trainingData[i][n-1] - predictedY
        print('Error = ', error)
        updatedTheta0 = theta0 + alpha * error * predictedY * (1-predictedY)
        for j in range(n-1):
            updatedTheta1[j] = theta1[j] + alpha * error * predictedY * (1-predictedY) * trainingInstance[j]
        theta0 = updatedTheta0
        theta1 = updatedTheta1
        print('theta0 = ', theta0)
        print('theta1 = ')
        print(numpy.transpose(theta1))
        print('\n')

(1, 4)
Training Instance =  [0.777291 0.579158 0.243856 0.030482]
PredictedY =  0.5
Actual Y=  0.0
Error =  -0.5
theta0 =  -0.0375
theta1 = 
[[-0.02914841 -0.02171842 -0.0091446  -0.00114307]]


Training Instance =  [0.79837  0.557353 0.225954 0.030127]
PredictedY =  0.48126459000924726
Actual Y=  0.0
Error =  -0.48126459000924726
theta0 =  -0.0735441648388489
theta1 = 
[[-0.05792499 -0.04180775 -0.01728892 -0.00222898]]


Training Instance =  [0.828133 0.50702  0.236609 0.033801]
PredictedY =  0.46334657381915295
Actual Y=  0.0
Error =  -0.46334657381915295
theta0 =  -0.10810840970135176
theta1 = 
[[-0.08654878 -0.05933251 -0.02546713 -0.00339728]]


Training Instance =  [0.803274 0.551267 0.220507 0.047251]
PredictedY =  0.4461805451337935
Actual Y=  0.0
Error =  -0.4461805451337935
theta0 =  -0.14118423748784936
theta1 = 
[[-0.11311774 -0.07756612 -0.03276059 -0.00496015]]


Training Instance =  [0.780109 0.576603 0.237425 0.050877]
PredictedY =  0.42991846953400437
Actual Y=  0.0
E

theta0 =  0.0653588248023188
theta1 = 
[[-0.0796021  -0.455793    0.76726522  0.32012309]]


Training Instance =  [0.826475 0.495885 0.264472 0.033059]
PredictedY =  0.49676301545551166
Actual Y=  0.0
Error =  -0.49676301545551166
theta0 =  0.028103160178292445
theta1 = 
[[-0.11039298 -0.47426753  0.75741214  0.31889146]]


Training Instance =  [0.733509 0.35453  0.550132 0.183377]
PredictedY =  0.5631954450699626
Actual Y=  1.0
Error =  0.43680455493003745
theta0 =  0.06034016657385136
theta1 = 
[[-0.08674684 -0.46283854  0.77514675  0.32480298]]


Training Instance =  [0.82225  0.517713 0.228403 0.060907]
PredictedY =  0.4865591546917234
Actual Y=  0.0
Error =  -0.4865591546917234
theta0 =  0.023874599968256457
theta1 = 
[[-0.11673066 -0.48171724  0.7668179   0.32258198]]


Training Instance =  [0.730814 0.347436 0.563086 0.167728]
PredictedY =  0.5639209990434852
Actual Y=  1.0
Error =  0.43607900095651475
theta0 =  0.05604599325240377
theta1 = 
[[-0.09321935 -0.47053974  0.78493316

In [168]:
#crisp predictions
def crispPredictions(predict):
    print(predict)
    if(predict < 0.5):
        crispPredict = 0
    else:
        crispPredict = 1
    print(crispPredict)
    return crispPredict

In [169]:
#test data for prediction
testm = testData.shape[0]
testn = testData.shape[1]
print('test m =', testm)
print('test n =', testn)
testInstance = numpy.zeros((1,n-1))
correct = 0
if(testn != n):
    print('Unequal number of features in train & testdata')
else:
    for testi in range(testm-1):
        testInstance = testData[testi][0:testn-1]
        testPredict = predict(theta0, theta1, testInstance)
        cp = crispPredictions(testPredict)
        print('Crisp Prediction by the algorithm = ', cp)
        actualTestPredict = testData[testi][testn-1]
        print('Actual value = ', actualTestPredict)
        if(cp == actualTestPredict):
            correct = correct +1
    print('Correct = ', correct)
    accuracy = (correct / testm) * 100
    print('Accuracy =',accuracy)

test m = 40
test n = 5
0.4002575126295256
0
Crisp Prediction by the algorithm =  0
Actual value =  0.0
0.5535161820688277
1
Crisp Prediction by the algorithm =  1
Actual value =  1.0
0.5449887270743491
1
Crisp Prediction by the algorithm =  1
Actual value =  1.0
0.4032475333056295
0
Crisp Prediction by the algorithm =  0
Actual value =  0.0
0.5706572311276267
1
Crisp Prediction by the algorithm =  1
Actual value =  1.0
0.3828055492209376
0
Crisp Prediction by the algorithm =  0
Actual value =  0.0
0.5501257158564468
1
Crisp Prediction by the algorithm =  1
Actual value =  1.0
0.4086783162211893
0
Crisp Prediction by the algorithm =  0
Actual value =  0.0
0.5360684298828489
1
Crisp Prediction by the algorithm =  1
Actual value =  1.0
0.41067711816884134
0
Crisp Prediction by the algorithm =  0
Actual value =  0.0
0.5545805402749205
1
Crisp Prediction by the algorithm =  1
Actual value =  1.0
0.4011206897846898
0
Crisp Prediction by the algorithm =  0
Actual value =  0.0
0.40568492092229